Connected to Python 3.13.0

In [ ]:
import numpy as np

with open('input_test.txt') as file:
    input = file.read()

In [ ]:
input

'2333133121414131402'

In [ ]:
mem = np.empty([1])

In [ ]:
mem

array([0.0078125])

In [ ]:
mem = np.empty()

TypeError: empty() missing required argument 'shape' (pos 0)

In [ ]:
mem = np.empty(1)

In [ ]:
mem

array([0.0078125])

In [ ]:
mem = np.empty(1 ,dtype=int)

In [ ]:
mem

array([4575657222473777152])

In [ ]:
mem.append(1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
np.append(mem, [1])

array([4575657222473777152,                   1])

In [ ]:
mem = np.array([])

In [ ]:
mem

array([], dtype=float64)

In [ ]:
np.append(mem, [1])

array([1.])

In [ ]:
mem = np.array([], dtype=int)

In [ ]:
np.append(mem, [1])

array([1])

In [ ]:
np.repeat(1, 2)

array([1, 1])

In [ ]:
1//2

0

In [ ]:
3//2

1

In [ ]:
(1 - 3 % 2) * (3//2) + (3%2) * -1

-1

In [ ]:
(3 % 2) * (3//2) + (1-3%2) * -1

1

In [ ]:
import numpy as np

with open('input_test.txt') as file:
    input = file.read()

mem = np.array([], dtype=int)
for i in range(len(input)):
    mem.repeat((3 % 2) * (3//2) + (1-3%2) * -1, mem[i])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
mem = np.array([], dtype=int)
for i in range(len(input)):
    mem.repeat((3 % 2) * (3//2) + (1-3%2) * -1, mem[i], axis=0)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
mem = np.array([], dtype=int)
for i in range(len(input)):
    np.append(mem, np.repeat(np.array[(3 % 2) * (3//2) + (1-3%2) * -1], mem[i], axis=0))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
mem = np.array([], dtype=int)
for i in range(len(input)):
    np.append(mem, np.repeat(np.array[(3 % 2) * (3//2) + (1-3%2) * -1], mem[i]))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
np.repeat((3 % 2) * (3//2) + (1-3%2) * -1, mem[i])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
i =2

In [ ]:
np.repeat((i % 2) * (i//2) + (1-i%2) * -1, mem[i])

IndexError: index 2 is out of bounds for axis 0 with size 0